[bumpversion]
commit = true
tag = true
current_version = "0.0.2"
message = "Bump version: {current_version} → {new_version} [skip ci]"

[bumpversion.file_patterns]
"src/package_name/__init__.py" = [
    {search = '__version__ = "{current_version}"', replace = '__version__ = "{new_version}"'},
]
